version: "3"

services:
  nginx-manager:
    image: txxsoura/swarm-nginx-load-balancer
    ports:
     - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: ["node.role == manager"]
  nginx-slave:
    image: nginx:alpine
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
